version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - docker-data:/data

    restart: always

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin_pass
      MYSQL_DATABASE: quran-app
      MYSQL_USER: root
      MYSQL_PASSWORD: admin_pass
    ports:
      - 3360:3306
    volumes:
      - docker-data:/var/lib/mysql
    restart: always

volumes:
  docker-data:
